#!/bin/bash
set -e
usage="$0 - Spotify Runner Helper

Controls spotify via DBUS, conforming to runner_general spec.

Actions:
  actions - List available commands for consumption by runner_general
    A tab delimited format of:
    [key]\t[command] [args]\t[description]\t[icon]\t[subtext]
"

action="$1"
shift
if [[ -z "$action" ]] || [[ "$action" == "-h" ]] || [[ "$action" == "--help" ]]; then
    echo "$usage" >&2
    exit 0
fi

function actions() {
    echo -e "lofi\tplay-uri playlist:74sUjcvpGfdOvCHvgzNEDO\tPlay Lofi Hip Hop Beats on Spotify\tmedia-playback-start\tmusic to study/relax to"
    echo -e "pause\tpause\tPause Spotify playback\tmedia-playback-pause"
    echo "META-CACHE=60"
}

function play-uri() {
    dbus-send \
    --type=method_call \
    --dest=org.mpris.MediaPlayer2.spotify \
    /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.OpenUri \
    "string:spotify:$1"
}

case "$action" in
    "actions")
        actions
        ;;
    "play-uri")
        play $@
        ;;
esac